// Field labels for DataReview (Hindi / English)

export const FIELD_LABELS: Record<string, { hi: string; en: string }> = {
  childName: { hi: 'बच्चे का नाम', en: 'Child Name' },
  fatherName: { hi: 'पिता का नाम', en: 'Father Name' },
  motherName: { hi: 'माता का नाम', en: 'Mother Name' },
  dateOfBirth: { hi: 'जन्म तिथि', en: 'Date of Birth' },
  dateOfDeath: { hi: 'मृत्यु तिथि', en: 'Date of Death' },
  placeOfBirth: { hi: 'जन्म स्थान', en: 'Place of Birth' },
  placeOfDeath: { hi: 'मृत्यु स्थान', en: 'Place of Death' },
  gender: { hi: 'लिंग', en: 'Gender' },
  hospitalName: { hi: 'अस्पताल का नाम', en: 'Hospital Name' },
  address: { hi: 'पता', en: 'Address' },
  district: { hi: 'जिला', en: 'District' },
  state: { hi: 'राज्य', en: 'State' },
  fatherAadhaar: { hi: 'पिता का आधार', en: "Father's Aadhaar" },
  motherAadhaar: { hi: 'माता का आधार', en: "Mother's Aadhaar" },
  deceasedName: { hi: 'मृतक का नाम', en: 'Deceased Name' },
  causeOfDeath: { hi: 'मृत्यु का कारण', en: 'Cause of Death' },
  age: { hi: 'आयु', en: 'Age' },
  fatherOrSpouseName: { hi: 'पिता/पति का नाम', en: "Father/Spouse Name" },
  applicantName: { hi: 'आवेदक का नाम', en: 'Applicant Name' },
  applicantRelation: { hi: 'आवेदक का संबंध', en: "Applicant's Relation" },
  currentAddress: { hi: 'वर्तमान पता', en: 'Current Address' },
  permanentAddress: { hi: 'स्थायी पता', en: 'Permanent Address' },
  residenceSinceYear: { hi: 'यहाँ रहने का वर्ष', en: 'Residence Since Year' },
  tehsil: { hi: 'तहसील', en: 'Tehsil' },
  village: { hi: 'गाँव', en: 'Village' },
  occupation: { hi: 'पेशा', en: 'Occupation' },
  annualIncome: { hi: 'वार्षिक आय', en: 'Annual Income' },
  sourceOfIncome: { hi: 'आय का स्रोत', en: 'Source of Income' },
  caste: { hi: 'जाति', en: 'Caste' },
  subCaste: { hi: 'उप-जाति', en: 'Sub-caste' },
  category: { hi: 'श्रेणी', en: 'Category' },
  husbandName: { hi: 'पति का नाम', en: "Husband's Name" },
  dateOfHusbandDeath: { hi: 'पति की मृत्यु तिथि', en: "Husband's Death Date" },
  bankAccountNumber: { hi: 'बैंक खाता संख्या', en: 'Bank Account Number' },
  ifscCode: { hi: 'IFSC कोड', en: 'IFSC Code' },
  bankName: { hi: 'बैंक का नाम', en: 'Bank Name' },
  branchName: { hi: 'शाखा का नाम', en: 'Branch Name' },
  farmerName: { hi: 'किसान का नाम', en: "Farmer's Name" },
  aadhaarNumber: { hi: 'आधार नंबर', en: 'Aadhaar Number' },
  mobileNumber: { hi: 'मोबाइल नंबर', en: 'Mobile Number' },
  khasraNumber: { hi: 'खसरा नंबर', en: 'Khasra Number' },
  landArea: { hi: 'जमीन का क्षेत्र', en: 'Land Area' },
  cropType: { hi: 'फसल का प्रकार', en: 'Crop Type' },
  headOfFamily: { hi: 'परिवार के मुखिया', en: 'Head of Family' },
  familyMembersCount: { hi: 'परिवार सदस्यों की संख्या', en: 'Family Members Count' },
  ward: { hi: 'वार्ड', en: 'Ward' },
  gasConnection: { hi: 'गैस कनेक्शन', en: 'Gas Connection' },
  serviceType: { hi: 'सेवा प्रकार', en: 'Service Type' },
};

export function getFieldLabel(fieldKey: string): { hi: string; en: string } {
  return FIELD_LABELS[fieldKey] || { hi: fieldKey, en: fieldKey };
}
