// Form selectors for CG eDistrict / government forms (aligned with formMappings.js)

export const FORM_SELECTORS: Record<string, Record<string, string>> = {
  birth_certificate: {
    childName: 'input[name="childName"], input[name="child_name"], #childName, #txtChildName',
    dateOfBirth: 'input[name="dob"], input[name="dateOfBirth"], #dob, #txtDOB, input[type="date"][name*="birth"]',
    gender: 'select[name="gender"], #gender, #ddlGender, input[name="gender"]',
    placeOfBirth: 'input[name="placeOfBirth"], #placeOfBirth, #txtPlaceOfBirth',
    fatherName: 'input[name="fatherName"], input[name="father_name"], #fatherName, #txtFatherName',
    motherName: 'input[name="motherName"], input[name="mother_name"], #motherName, #txtMotherName',
    fatherAadhaar: 'input[name="fatherAadhaar"], #fatherAadhaar',
    motherAadhaar: 'input[name="motherAadhaar"], #motherAadhaar',
    hospitalName: 'input[name="hospitalName"], #hospitalName, #txtHospitalName',
    address: 'textarea[name="address"], input[name="address"], #address, #txtAddress',
    district: 'select[name="district"], #district, #ddlDistrict',
    state: 'select[name="state"], #state, #ddlState',
  },
  death_certificate: {
    deceasedName: 'input[name="deceasedName"], #deceasedName, #txtDeceasedName',
    dateOfDeath: 'input[name="dateOfDeath"], #dateOfDeath, #txtDateOfDeath',
    placeOfDeath: 'input[name="placeOfDeath"], #placeOfDeath',
    causeOfDeath: 'input[name="causeOfDeath"], select[name="causeOfDeath"], #causeOfDeath',
    gender: 'select[name="gender"], #gender, #ddlGender',
    age: 'input[name="age"], #age, #txtAge',
    fatherOrSpouseName: 'input[name="fatherOrSpouseName"], #fatherOrSpouseName',
    address: 'textarea[name="address"], input[name="address"], #address',
    applicantName: 'input[name="applicantName"], #applicantName',
    applicantRelation: 'select[name="applicantRelation"], #applicantRelation',
  },
  domicile_certificate: {
    applicantName: 'input[name="applicantName"], #applicantName, #txtApplicantName',
    fatherName: 'input[name="fatherName"], #fatherName, #txtFatherName',
    dateOfBirth: 'input[name="dob"], #dob, #txtDOB',
    gender: 'select[name="gender"], #gender, #ddlGender',
    currentAddress: 'textarea[name="currentAddress"], #currentAddress',
    permanentAddress: 'textarea[name="permanentAddress"], #permanentAddress',
    residenceSinceYear: 'input[name="residenceSince"], #residenceSince',
    district: 'select[name="district"], #district, #ddlDistrict',
    tehsil: 'select[name="tehsil"], #tehsil, #ddlTehsil',
    village: 'input[name="village"], select[name="village"], #village',
  },
  income_certificate: {
    applicantName: 'input[name="applicantName"], #applicantName, #txtApplicantName',
    fatherName: 'input[name="fatherName"], #fatherName, input[name="54"], #54',
    occupation: 'input[name="occupation"], select[name="occupation"], #occupation, select[name="126"], #126',
    annualIncome: 'input[name="annualIncome"], #annualIncome, input[name="128"], #128',
    sourceOfIncome: 'input[name="sourceOfIncome"], #sourceOfIncome',
    address: 'textarea[name="address"], input[name="address"], #address',
    district: 'select[name="district"], #district, #ddlDistrict, select[name="196"], #196',
    tehsil: 'select[name="tehsil"], #tehsil, #ddlTehsil',
  },
  caste_certificate: {
    applicantName: 'input[name="applicantName"], #applicantName',
    fatherName: 'input[name="fatherName"], #fatherName',
    caste: 'input[name="caste"], select[name="caste"], #caste',
    subCaste: 'input[name="subCaste"], #subCaste',
    category: 'select[name="category"], #category',
    address: 'textarea[name="address"], input[name="address"], #address',
    district: 'select[name="district"], #district',
    tehsil: 'select[name="tehsil"], #tehsil',
    village: 'input[name="village"], #village',
  },
  old_age_pension: {
    applicantName: 'input[name="applicantName"], #applicantName',
    fatherOrSpouseName: 'input[name="fatherOrSpouseName"], #fatherOrSpouseName',
    dateOfBirth: 'input[name="dob"], #dob, #dateOfBirth',
    age: 'input[name="age"], #age',
    gender: 'select[name="gender"], #gender',
    address: 'textarea[name="address"], input[name="address"], #address',
    bankAccountNumber: 'input[name="bankAccountNumber"], #bankAccountNumber, input[name*="account"]',
    ifscCode: 'input[name="ifscCode"], #ifscCode, input[name*="ifsc"]',
    bankName: 'input[name="bankName"], #bankName',
    branchName: 'input[name="branchName"], #branchName',
  },
  widow_pension: {
    applicantName: 'input[name="applicantName"], #applicantName',
    husbandName: 'input[name="husbandName"], #husbandName',
    dateOfBirth: 'input[name="dob"], #dob',
    age: 'input[name="age"], #age',
    dateOfHusbandDeath: 'input[name="dateOfHusbandDeath"], #dateOfHusbandDeath',
    address: 'textarea[name="address"], input[name="address"], #address',
    bankAccountNumber: 'input[name="bankAccountNumber"], #bankAccountNumber',
    ifscCode: 'input[name="ifscCode"], #ifscCode',
    bankName: 'input[name="bankName"], #bankName',
  },
  kisan_registration: {
    farmerName: 'input[name="farmerName"], #farmerName, input[name*="name"]',
    fatherName: 'input[name="fatherName"], #fatherName',
    aadhaarNumber: 'input[name="aadhaarNumber"], #aadhaarNumber, input[name*="aadhaar"]',
    mobileNumber: 'input[name="mobileNumber"], #mobileNumber, input[name*="mobile"]',
    village: 'input[name="village"], #village',
    tehsil: 'select[name="tehsil"], #tehsil',
    district: 'select[name="district"], #district',
    khasraNumber: 'input[name="khasraNumber"], #khasraNumber, input[name*="khasra"]',
    landArea: 'input[name="landArea"], #landArea',
    cropType: 'input[name="cropType"], select[name="cropType"]',
    bankAccountNumber: 'input[name="bankAccountNumber"], #bankAccountNumber',
    ifscCode: 'input[name="ifscCode"], #ifscCode',
  },
  ration_card: {
    headOfFamily: 'input[name="headOfFamily"], #headOfFamily',
    fatherOrSpouseName: 'input[name="fatherOrSpouseName"], #fatherOrSpouseName',
    address: 'textarea[name="address"], input[name="address"], #address',
    familyMembersCount: 'input[name="familyMembersCount"], #familyMembersCount',
    annualIncome: 'input[name="annualIncome"], #annualIncome',
    category: 'select[name="category"], #category',
    district: 'select[name="district"], #district',
    ward: 'input[name="ward"], #ward',
    gasConnection: 'input[name="gasConnection"], #gasConnection',
  },
  other: {
    applicantName: 'input[name="applicantName"], #applicantName',
    fatherName: 'input[name="fatherName"], #fatherName',
    address: 'textarea[name="address"], input[name="address"], #address',
    district: 'select[name="district"], #district',
    serviceType: 'input[name="serviceType"], select[name="serviceType"]',
  },
};

export function getFormSelectors(backendServiceId: string): Record<string, string> {
  return FORM_SELECTORS[backendServiceId] || FORM_SELECTORS.other;
}
